# PostgreSql 설정
spring.datasource.url=jdbc:postgresql://localhost:15432/msa_service
spring.datasource.username=khube
spring.datasource.password=khube
spring.datasource.driver-class-name=org.postgresql.Driver

# 로컬 서버 포트
server.port=18080