# PostgreSql 설정
spring.datasource.url=jdbc:postgresql://postgresql:5432/msa_service
spring.datasource.username=khube
spring.datasource.password=khube
spring.datasource.driver-class-name=org.postgresql.Driver

# Docker에서 기본 포트 사용
server.port=8080