# PostgreSql ì¤ì 
spring.datasource.url=jdbc:postgresql://postgresql:5432/msa_service
spring.datasource.username=khube
spring.datasource.password=khube
spring.datasource.driver-class-name=org.postgresql.Driver

# Dockerìì ê¸°ë³¸ í¬í¸ ì¬ì©
server.port=8082

eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true