# PostgreSql ì¤ì 
spring.datasource.url=jdbc:postgresql://localhost:15432/msa_service
spring.datasource.username=khube
spring.datasource.password=khube
spring.datasource.driver-class-name=org.postgresql.Driver

# ë¡ì»¬ ìë² í¬í¸
server.port=18082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true