spring.application.name=order-server

# PostgreSql 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/msa_service
spring.datasource.username=khube
spring.datasource.password=khube
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 지역 설정
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# 로그
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE