services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: khube
      POSTGRES_PASSWORD: khube
      POSTGRES_DB: msa_service
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - khube-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - khube-network

volumes:
  postgres_data:
  redis_data:

networks:
  khube-network:
    driver: bridge